version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    target-branch: master
    schedule:
      interval: daily
      time: '14:00'
      timezone: Europe/Bratislava
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 99
