name: Go

on: [ pull_request ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - uses: evantorrie/mott-the-tidier@v1-beta

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: go mod tidy
